### ISSUE TITLE
build pack error  - citydby 

### ISSUE THREAD

**Issue by worldquest** [SAP-samples/cloud-foundry-cap-azure-cities#18]
Hi team,

Does anyone face the package build error for city-cap-db ? 

#2.0#2020 05 12 09:14:02.332#Z#DEBUG#com.sap.cloud.lm.sl.xs2.63341507-9430-11ea-8ded-eeee0a9bab7b.city-cap-db.stageAppTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-29###
[PollStageAppStatusExecution] [city-cap-db] 337873b4-1f98-4fbe-a29c-1e762fd5c3d0 [Tue May 12 09:13:53 UTC 2020] -----> Nodejs Buildpack version 1.7.15 (STDOUT, STG)#

#2.0#2020 05 12 09:14:02.332#Z#DEBUG#com.sap.cloud.lm.sl.xs2.63341507-9430-11ea-8ded-eeee0a9bab7b.city-cap-db.stageAppTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-29###
[PollStageAppStatusExecution] [city-cap-db] 337873b4-1f98-4fbe-a29c-1e762fd5c3d0 [Tue May 12 09:13:54 UTC 2020] -----> Installing binaries (STDOUT, STG)#

#2.0#2020 05 12 09:14:02.332#Z#DEBUG#com.sap.cloud.lm.sl.xs2.63341507-9430-11ea-8ded-eeee0a9bab7b.city-cap-db.stageAppTask#
######com.sap.cloud.lm.sl.cf.persistence.services.ProcessLogger########flowable-async-job-executor-thread-29###
[PollStageAppStatusExecution] [city-cap-db] 337873b4-1f98-4fbe-a29c-1e762fd5c3d0 [Tue May 12 09:13:54 UTC 2020]        [31;1m**ERROR**[0m Unable to install node: no match found for ^8 in [10.18.1 10.19.0 12.16.0 12.16.1 13.10.1 13.11.0] (STDOUT, STG)#

**Comment by maxstreifeneder** [comment]
working on a fix :-) will come back to you tomorrow or the day after

**Comment by maxstreifeneder** [comment]
Hi @worldquest,

could you please try it again? Released version 1.7.4 yesterday: https://github.com/SAP-samples/cloud-foundry-cap-azure-cities/releases/tag/1.7.4

Cheers,
Max

**Comment by worldquest** [comment]
HI @maxstreifeneder   

many thanks for your revision. but i see a new exception. 

B. Rgds

Chanjin



cds] - building project [/home/chan/cloud-foundry-cap-azure-cities], clean [true]

[cds] - cds [3.34.1], compiler [1.26.2], home [/home/chan/cloud-foundry-cap-azure-cities/node_modules/@sap/cds]
[cds] - Build error: Failed to create BuildTaskHandler [@sap/cds/lib/build/node-cf]
SyntaxError: Invalid regular expression: /^(?:(?:_|\p{Letter}|\p{Letter_Number})(?:_|\p{Letter}|\p{Letter_Number}|\p{Decimal_Number}|\p{Nonspacing_Mark}|\p{Spacing_Mark}|\p{Connector_Punctuation}|\p{Format}){0,127})/: Invalid escape
[INTERNAL ERROR] SyntaxError: Invalid regular expression: /^(?:(?:_|\p{Letter}|\p{Letter_Number})(?:_|\p{Letter}|\p{Letter_Number}|\p{Decimal_Number}|\p{Nonspacing_Mark}|\p{Spacing_Mark}|\p{Connector_Punctuation}|\p{Format}){0,127})/: Invalid escape
    at new RegExp (<anonymous>)
    at Object.<anonymous> (/home/chan/cloud-foundry-cap-azure-cities/node_modules/@sap/odata-server/node_modules/@sap/odata-commons/lib/uri/UriTokenizer.js:8:27)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/chan/cloud-foundry-cap-azure-cities/node_modules/@sap/odata-server/node_modules/@sap/odata-commons/lib/uri/KeyValueParser.js:7:19)
Please report this error.



0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:cf' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 verbose run-script [ 'predeploy:cf', 'deploy:cf', 'postdeploy:cf' ]
5 info lifecycle city-explorer-demo-app@1.7.6~predeploy:cf: city-explorer-demo-app@1.7.6
6 info lifecycle city-explorer-demo-app@1.7.6~deploy:cf: city-explorer-demo-app@1.7.6
7 verbose lifecycle city-explorer-demo-app@1.7.6~deploy:cf: unsafe-perm in lifecycle true
8 verbose lifecycle city-explorer-demo-app@1.7.6~deploy:cf: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/chan/cloud-foundry-cap-azure-cities/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/linkerd/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/istio-latest/bin:/usr/local/go/bin:/opt/mssql-tools/bin:~/bundle/bin:~/bundle/gems/bin
9 verbose lifecycle city-explorer-demo-app@1.7.6~deploy:cf: CWD: /home/chan/cloud-foundry-cap-azure-cities
10 silly lifecycle city-explorer-demo-app@1.7.6~deploy:cf: Args: [ '-c',
10 silly lifecycle   'npm run build:mta && cf deploy mta_archives/city-explorer-demo-app.mtar' ]
11 silly lifecycle city-explorer-demo-app@1.7.6~deploy:cf: Returned: code: 1  signal: null
12 info lifecycle city-explorer-demo-app@1.7.6~deploy:cf: Failed to exec deploy:cf script
13 verbose stack Error: city-explorer-demo-app@1.7.6 deploy:cf: `npm run build:mta && cf deploy mta_archives/city-explorer-demo-app.mtar`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid city-explorer-demo-app@1.7.6
15 verbose cwd /home/chan/cloud-foundry-cap-azure-cities
16 verbose Linux 4.15.0-1082-azure
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy:cf"
18 verbose node v8.16.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error city-explorer-demo-app@1.7.6 deploy:cf: `npm run build:mta && cf deploy mta_archives/city-explorer-demo-app.mtar`
22 error Exit status 1
23 error Failed at the city-explorer-demo-app@1.7.6 deploy:cf script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by maxstreifeneder** [comment]
hi @worldquest, 

is this problem still occuring? there were several updates to the tools. 

Regards,
Max
